# This file was generated by GoReleaser. DO NOT EDIT.
cask "ngris" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "9dde515a57f583f8a7c7507014424512b5d851eddc194b7a194463e12c8ac513"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "46b33c99f991029622326b442e9c58412fd2a56b87de99fcdb461bb2cfac61ed"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "76cb534f2804667495ba9db14d5166d00793b9b8a581023eb6e9280a34cf886c"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ae41433603fe2a31f0ac814fea30c968a84586b79b30af3318dd36263000619"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_linux_amd64.tar.gz"
    end
  end

  name "ngris"
  desc "Ngris agent — expose local services and run an edge API gateway."
  homepage "https://ngris.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ngris"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ngris"]
    end
  end

  # No zap stanza required
end
