# This file was generated by GoReleaser. DO NOT EDIT.
cask "ngris" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "e4410335a011cd48eed36dd6f7875080f2215a9a9da6eef2eb06842aa0319edf"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "29e66e9f570c4f5b0ccf630f85c0903ec9fcb3e8488a5d215877a0b3a6a541f0"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "040ca8b938aa71d284a2c1b618d89a3f327c50024206d0e71ff3595bd553bff1"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "690df60872c60a8a4181bf5d0bba7354a9344a0f60c26efcc585e078d3f4ac4e"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_linux_amd64.tar.gz"
    end
  end

  name "ngris"
  desc "Ngris agent — expose local services and run an edge API gateway."
  homepage "https://ngris.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ngris"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ngris"]
    end
  end

  # No zap stanza required
end
