# This file was generated by GoReleaser. DO NOT EDIT.
cask "ngris" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "712f7e571ec2204113ca43e5385a7d3506e8c84cec8837ad320cb321d18c19ed"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b703c704e8680f049c56291966267ac7eafd23da746fcdee5e8bfd7428a9138"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6496505872bde1c21ecdb138623e308b8696e62b0ff3fccb6f00eaa9bcb76e6"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a52abd946dfeadeb2039e9ff21ef9fd1b5f4f6573a468ef789e5df4fe548e62"
      url "https://github.com/ngris-edge/ngris/releases/download/v#{version}/ngris_linux_arm64.tar.gz"
    end
  end

  name "ngris"
  desc "Ngris agent — expose local services and run an edge API gateway."
  homepage "https://ngris.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ngris"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ngris"]
    end
  end

  # No zap stanza required

end
